### ISSUE TITLE
Fall24 Meeting Notes

### ISSUE THREAD

**Issue by cvancil** [UCSB-Exoplanet-Polarimetry-Lab/ConnorThesis#2]
### September 16 (Pre-MOSFIRE Observing Notes)
- [x]  set up repositories for all proj. & link to Project
- [x] Figure out if linking Overleaf draft is worth it
- [x] MOSFIRE Observing prep: 
   - [x] Set up observing log from Template
   - [x] reach out to Jim: explain goals of night, explain variability program, ask to check masks
   - [x] add links to logs and such through SIMP/MOSFIRE observing repo
   - [x] fill in observing plan
   - [x] ask Justin if he'd like to call in - what are the more specific goals of his program, maybe he could help/take ovver live
      - [x] offer to do data reduction & iterate w/ how he wants to interpret data 
   - [x] **formulate a question about slit sizes for Elena: waht slit size wdo we prefer 4.5 or 1 (HIGH priority)** 
   - [x] find A star and figure out what mask we should use (long2pos ?)
   - [x] BUILD MOSFIRE REPOSITORY
  
maybe start overleaf and fill out observing section in real time?

**Comment by cvancil** [comment]
From Max: Here's the link to the March 2022 MOSFIRE Observing Folder: https://drive.google.com/drive/folders/1Ypgvl7HfNj00YL9dUez4WHsxH2VpzMAD

PreObserving Tasks (in-person)

- [x] Apply pm to KapAnd
- [x] get KapAnd offsets from whereistheplanet.com
- [x] set up live-data download 
- [x] set up Zoom & screenshare on mokupuni for Justin

IntraObserving Tasks

- [x] work on Luhman 16 Repo
- [x] Closer look at L16 separated Lightcurves version 2
- [x] In-depth L16 Timeline & task list
- [x] Notes on the OSIRIS?MOSFIRE Observing planning process
- [x] Updates on Polarimetry vs Photometry notebook?
- [x] Wheel of Time (?)
- [x] Try to install pype-it for MOSFIRE Data reduction

**Comment by maxwellmb** [comment]
### September 30

Completed Items and Updates: 
- [x] Reduce and Send off OSIRIS Data
- [x] Get Pypeit up and running
- [x] Start reducing MOSFIRE data
- [x] Get computing account set up

Todo-list Items from Last Meeting: 
- [x] set up repositories for all proj. & link to Project
- [x] Figure out if linking Overleaf draft is worth it

New Action Items: 
- [x] Finish preliminary MOSFIRE Data reduction 
- [ ] Restructuring Max's (post supercomputer script) code
- [x] Test supercomputer with one wavelength
- [x] EPSF Fitting GROND NIR Data (8 hours)  
- [ ] More complete outline of Overleaf Paper
- [x] Establish Test for output of supercomputer -> Compare it directly apples to apples with something from UCF.  
- [x] Reach out to James about AstroTea

**Comment by cvancil** [comment]
### October 3

Completed Items and Updates:
- [x] Figure out if linking Overleaf draft is worth it
- [x] Finish preliminary MOSFIRE Data reduction 
- [x] Establish Test for output of supercomputer -> Compare it directly apples to apples with something from UCF.  
- [x] Reach out to James about AstroTea

Todo-list Items from Last Meeting:

- [x] set up repositories for all proj. & link to Project
- [ ] Restructuring Max's (post supercomputer script) code
- [x] EPSF Fitting GROND NIR Data (8 hours)  
- [ ] More complete outline of Overleaf Paper

New Action Items:

- [x] Make HWO Polarimetry Modeling repo
- [x] Review, install, test existing hwo-tools code
- [x] Conduct test of ARTES run w/ Max G.
- [x] Write up of starting CSC process (short task)
- [x] add modeling google sheet to luhman 16 repo
- [x] annual update form is late, Zvonimir asking for it
- [x] find solar system planet as exoplanet color plot in some astro biology paper (maybe)
    - this one is qualitative: https://science.nasa.gov/resource/visible-light-color-of-planets-plot/
    - another qualitative example: https://www.nasa.gov/centers-and-facilities/goddard/using-planet-colors-to-search-for-alien-earths/
    - Look at Figure 7 here: https://www.liebertpub.com/doi/10.1089/ast.2017.1763
    - Maybe Figure 10 here too: https://iopscience.iop.org/article/10.1088/0004-637X/729/2/130/pdf

**Comment by cvancil** [comment]
### October 7

Completed Items and Updates:

- [x] Make HWO Polarimetry Modeling repo
- [x] Review, install, test existing hwo-tools code
- [x] find solar system planet as exoplanet color plot in some astro biology paper 
- [x] Write up of starting CSC process (short task)
- [x] add modeling google sheet to luhman 16 repo

Todo-list Items from Last Meeting:

- [x] Conduct test of ARTES run w/ Max G.
- [ ] ~~Restructuring Max's (post supercomputer script) code~~ move to longer term goals
- [ ] EPSF Fitting GROND NIR Data #UCSB-Exoplanet-Polarimetry-Lab/Luhman16_NACO_GROND#2
- [ ] More complete outline of Overleaf Paper

New Action Items:

- [x] HWO ETC tasks: #UCSB-Exoplanet-Polarimetry-Lab/HWO_Polarimetry_Modeling#2 (to report on at next Tuesday meeting)
- [x] Understand ETC code + outputs
- [x] form + email update committee
- [ ] hold update meeting

**Comment by cvancil** [comment]
### October 10

Completed Items and Updates:

- [x] Conduct test of ARTES run w/ Max G.
- [x] HWO ETC tasks: #UCSB-Exoplanet-Polarimetry-Lab/HWO_Polarimetry_Modeling#2 (to report on at next Tuesday meeting)
- [x] Understand ETC code + outputs
- [x] form + email update committee
- [x] Fix ARTES modeling problems - we are now modeling at full resolution with no problems!

Todo-list Items from Last Meeting:

- [x] hold update meeting (upcoming once scheduled)
- [ ] More complete outline of Overleaf Paper
- [ ] EPSF Fitting GROND NIR Data #UCSB-Exoplanet-Polarimetry-Lab/Luhman16_NACO_GROND#2 (happening today!)

New Action Items:
- [x] HWO ETC meeting on Tuesday
- [x] L16 Modeling Strategy now that CSC + ARTES fully running

Less new action items since I want to wrap up the ones that have been on here for a while

**Comment by cvancil** [comment]
### October 14

Completed Items and Updates: 

- [x] Tasks from: EPSF Fitting GROND NIR Data #UCSB-Exoplanet-Polarimetry-Lab/Luhman16_NACO_GROND#2
- [x] Full run of ARTES 

Todo-list Items from Last Meeting:

- [ ] Luhman16 Overleaf Paper outline
- [x] Friday Annual Update Meeting
- [x] HWO ETC meeting Tuesday (tasks to stem from this)
- [x] L16 Modeling Strategy

New Action Items:

- [x] Correct "model" light curves with reference stars
- [ ] Ask UCSB computing folks the modeling code is so much slower than on a laptop
- [x] Fork SYOTools repository to exoplanet polarimetry lab, and write simple usage notebook
- [x] #UCSB-Exoplanet-Polarimetry-Lab/HWO_Polarimetry_Modeling#3

**Comment by cvancil** [comment]
### Goals for day of October 22

General and Luhman 16:

- [x] Emails & admin
- [x] Verify new model base & create new slurm job scripts
- [x] Submit slurm job scripts
- [x] finish model db generation
- [x] Get verification file from Max (photometry.dat)
- [x] Send Max Modeling Plan
- [x] UCSB training module

note: bring "rewrite Max post-processing scripts" back into task rotation

HWO ETC:

- [x] write simple usage notebook for coron_imaging
- [x] analyze outputs from simple usage notebook ("core_mean_intensity requires core_platescale to be set in system coronagraph", The following outspec keywords were not used in any module init: default_vals_extra (Nemati))
- [x] get pol inputs from Kenny (awaiting response), think about architecture to accept custom spectra
- [ ] pins in code where including pol mode would necessitate changes
- [x] read (skim) Kenny modeling paper

From Kenny: 
- "The attached zip files are for models in each of the four eons of Earth. Each eon then contains individual folders for each specific model run, and each individual folder then contains the .dat files for the unpolarized and polarized spectra for each phase angle. I have also attached a README.txt file that describes everything in more detail. "
- We are also working on getting some giant planet models prepared to send to you as well. Once we have those prepared (I think Theodora and Max are still running some stuff), we can send them your way!

**Comment by cvancil** [comment]
### October 24

Completed Items and Updates:

- [x] Bunch of tasks and updates on L16 Modeling
- [x] Some updates to L16 Paper draft

Todo-list Items from Last Meeting:

- [ ] Luhman 16 Paper (draft started)
- [x] Rewrite Max's Post-Processing Scripts (now relevant again)
- [ ] HWO-tools polarimetry flags
- [ ] Comments on Simple Usage notebook

New Action Items:

- [x] Review Max ARTES code bug - does this negate the modeling done so far?
- [x] Turn above into a GitHub Issue (done, see #UCSB-Exoplanet-Polarimetry-Lab/Luhman16_NACO_GROND#3)
- From HWO slack: "High-C ETC development notes: Max Millar-Blanchaer’s student is identifying the EXOSIMS input parameters and which ones should and should not be varied."
- [x] Fold comments from Simple Usage notebook into exosims_wrapper
- [x] Push Updates to main HWO repo (sync changes w/ fork)
- [x] Discuss Ideas w/ Max regarding Polarimetry vs. Photometry (what tools, what signal, etc)
    - [ ] cross correlate, Q, U, P, theta
    - [ ] residuals Pol data - mcmc fit
    - [ ] residuals as function of night (how does P change over time)
- [x] Separate pull request to remove unnecessary parameters (radDos, OWA, etc)
- [x] what parameters can we tune and what parameters do we not expect to? Create a table (markdown?) to list used & unused


New Tasks as of 10/29:

- [ ] Hack EXOSIMS to take user-generated spectra
- [ ] Simple polarimetry notebook in hwo-tools
- [x] Finish PostProcessing Cloud Code
- [x] Rewrite ARTES modeling code, run opacities separately - can I make each of these a subtask?
- [x] port multipleopacity edits to pod & start new run
- [ ] get external HD for model storage

**Comment by cvancil** [comment]
### October 31 👻🕷️

Tasks from 10/29:

Todo-list Items from Last Meeting:

 - [x] Review Max ARTES code bug
 - [x] EXOSIMS Parameter Table
 - [x] Finish PostProcessing Cloud Code - Can now create Spotted/Banded Cloud Models! 
- [x] Rewrite ARTES modeling code, run opacities separately
- [x] port multipleopacity edits to pod & start new run
- [ ] Hack EXOSIMS/hwo-tools to take user-generated spectra
- [ ] Simple polarimetry notebook in hwo-tools
- [x] get external HD for model storage (bug Skyler on gateway)
- [ ] L16AB Comparing Polarimetry/Photometry (Task for Week of 11/3)
    - [ ] cross correlate, Q, U, P, theta
    - [ ] residuals Pol data - mcmc fit
    - [ ] residuals as function of night (how does P change over time)

New Action Items:

- read Mennesson and Stark papers 
- [ ] Mennesson
- [ ] Stark
- Make a notebook that gives:
- [ ] ETC based on SNR
     - [ ] ETC to get SNR of 10 on earthlike planet as a function of distance from the earth (total intensity)
     - [ ] THEN (do this after the above, maybe) find a plot from Mennesson/Stark Papers and pick a plot to reproduce

**Comment by cvancil** [comment]
### November 4

Completed Items and Updates:

- [x] get external HD for model storage (bug Skyler on gateway)
- [x] started new separate-opacity model runs, updated modeling spreadsheet

Todo-list Items from Last Meeting:
- [ ] L16AB Comparing Polarimetry/Photometry (Task for Week of 11/3)
    - [ ] cross correlate, Q, U, P, theta
    - [ ] residuals Pol data - mcmc fit
    - [ ] residuals as function of night (how does P change over time)
- read Mennesson and Stark papers 
- [x] Mennesson
- [ ] Stark
- Make a notebook that gives:
- [ ] ETC based on SNR
     - [x] ETC to get SNR of 10 on earthlike planet as a function of distance from the earth (total intensity)
     - [x] similar figure for EXOSIMS
     - [x] THEN (do this after the above, maybe) find a plot from Mennesson/Stark Papers and pick a plot to reproduce 

New Action Items:

- Observing
- [x] Invite Ryan and Undergrads to observing
- [x] ask for MOSFIRE switch over (cc max on email)
- [ ] Science Target(s) for extra time (IMPORTANT, DO SOON)
- [x] define Pre-Observing Checklist

Pre-Observing Checklist:
- [x] Update target coords (all in SIMP Mask (?))
- [ ] Get target list ready to send (add SIMPMask center coords, get backup targets)
- [ ] Create MOSFIRE SIMP Masks w/ updated coords
- [x] Create Observing Documents (log, narrative log, observing plan)
- [ ] Verify observing plan w/ Max and Randy (Keck support astronomer)
- [x] Update Ryan Hersey (and undergrads if they respond) on progress when the above are complete 
- [ ] It would be good to update SIMP slide deck with figures from prev years (look in ~/Astro/Data/Osiris_20231005/), use these to explain observations + progress to Ryan and to refresh memory
- [x] Ask Max about later observing nights for Thomas

**Comment by cvancil** [comment]
### November 7

Completed Items and Updates:

- [x] ETC to get SNR of 10 on earthlike planet as a function of distance from the earth (total intensity)
- [x] similar figure for EXOSIMS
- [x] Invite Ryan and Undergrads to observing
- [x] ask for MOSFIRE switch over (cc max on email)
- [x] define Pre-Observing Checklist
- [x] Update target coords (all in SIMP Mask (?))
- [x] Create Observing Documents (log, narrative log, observing plan)
- [x] Update Ryan Hersey (and undergrads if they respond) on progress when the above are complete 

Todo-list Items from Last Meeting:

- [ ] L16AB Comparing Polarimetry/Photometry (ongoing)
    - [ ] cross correlate, Q, U, P, theta
    - [x] residuals Pol data - mcmc fit
    - [x] residuals as function of night (how does P change over time)
- [x] Get target list ready to send (add SIMPMask center coords, get backup targets)
- [x] Create MOSFIRE SIMP Masks w/ updated coords
- [x] Verify observing plan w/ Max and Randy (Keck support astronomer)
- [x] Fill in extra observing time

New Action Items:

- With Kenny's Models:
     - [x] Use UVBRI filter curves to bin down models
     - [ ] What is the color of polarimetry? Could be as simple as (relative/normalized) pol. brightness in each filter as a function of phase angle
     - [x] What plots to create?
          - I can now get average flux over bandpass as a function of phase angle & model. Need to determine appropriate scaling factor ( in notes, probably set objects at 10pc with Earth flux) & interface with Theodora + Kenny
- [x] Send Thomas pre-observing links

**Comment by cvancil** [comment]
### Nov 12

Completed Items and Updates: 

- [x] Fill out observing plan & update observing group
- [x] Other observing tasks (slit masks, MOSFIRE starlists, etc.)
- [x] Kenny's models: Use UVBRI filter curves to bin down models, can now give I,Q,P brightness as function of phase angle and filter for a given model type (used Bessell UVBRIJH filter curves)

Todo-list Items from Last Meeting:

- [ ] cross correlate L16 Q, U, P, theta (during the week or during observing)
- [x] Create Plots for color of polarimetry idea
- [x] check notes for Kenny model scaling factor -> targets can be scaled with r, d, F_0 (radius/separation, distance to target, incident stellar flux)

New Action Items:

- [x] Upload slit masks to Keck
- [x] Update SIMP slides for observing guests (2023 slides summarize progress well so far)
- [ ] Make NGS Starlist from Quinn targets
- [ ] Contact JT, should I provide a slide for next week's meeting summarizing my efforts so far (I'd ideally like some feedback on EXOSIMS parameters first)
- [ ] Talk w/ Max & JT for ETC next steps (EXOSIMS or syotools for calculations?, should I be making steps that will apply to released ETC or focus on ETC calculations for Kenny paper)
- [x] determine list of intra-observing tasks
- [ ] parallelization for new BDCloud Model runs? (these are taking FAR too long after opacity changes)

**Comment by cvancil** [comment]
### Nov 14

Completed Items and Updates:
- [x] Create Plots for color of polarimetry idea
- [x] check notes for Kenny model scaling factor -> targets can be scaled with r, d, F_0 (radius/separation, distance to target, incident stellar flux)
- [x] done w/ observing prep (minus NGS target list)

Todo-list Items from Last Meeting:
- [x] Make NGS Starlist from Quinn targets
- [x] Contact JT, should I provide a slide for next week's meeting summarizing my efforts so far (I'd ideally like some feedback on EXOSIMS parameters first)
- [x] Talk w/ Max & JT for ETC next steps (EXOSIMS or syotools for calculations?, should I be making steps that will apply to released ETC or focus on ETC calculations for Kenny paper)
- [x] parallelization for new BDCloud Model runs?

New Action Items:
- [ ] Find Some H-band spectra of L16AB to determine important wavelengths (may want to lower number of wavelengths getting modeled)
- [ ] Read HWO Science case documents
- [x] what is Kenny model Ps?
     - Ps = -Q/F
- [x] determine Kenny model scaling factor
     - F (the one I have) = 1/4 * r^2/d^2 * Scattering matrix * F0 (incident starlight flux vector)
- [x] with V and R-bands, see how degree of polarization is diagnostic, plot v pol at x degrees, vs r pol at 90 degrees, for a bunch of models (90 degrees), V(phase angle) for bunch of models
     - [x] what are the diagnostic measurments here, maybe look at B and I as well (harder to observe these), what helps us distinguish between earth types or atmospheres
     -  the code to make these plots is ready - I just need to convert fluxes into exposure times with HWOtools or EXOSIMS, waiting for ETC WG update
 - Max's questions about noise: each "rotation" where cloud isn't in view isn't a different realization of noise - we see no scatter in errorbars or data points because we're using the same data + noise = highly correlated noise across phase
      - [ ] make a map/chart of how noise is calculated (why 2-D maps after ARTES)
      - [x] can talk w/ Max G. about updating noise realizations at each data point 
      - size of error bars >> change in Q/U, meaning actual changes in Q/U we are seeing are noise & would not be reflected in another realization of the same atmosphere
      - I should consider how noise is getting propagated from output of ARTES through the many layers of averaging and finally into those Q/U curves
      -  I did a very quick and dirty reduction to get those curves, but should come up with something more robust (look again at Max's paper)

Intra-Observing Tasks
- [x] SIMP-MOSFIRE Data Analysis REU Project Description
- [ ] Make Notes of MOSFIRE data reduction process
- [ ] BD Clouds Test: Downsample L16Grond Data to picaso-model native resolution
     - [ ] can we spot the same variability in low res models?
     - [ ] Try this on the cleaned, EPSF Separated LCs as well
     - [ ] build an intuition for what information the models can replicate
- [ ] NACO Cross-Correlation

Post-HWO Meeting Tasks:
- [ ] use syo-tools & coronagraph tools to further the ETC goals
     - in the simplest case, this looks like a new function in the current hwo-tools directory.
     - in a more developed way, this could be a set of syotools files
     - Since we don't know the future of the codes & its the effort that counts currently, I'll do the simple case 
- [ ] plug the average-polarized fluxes into that ETC and get SNRs for Kenny data 
- [x] add top-level defaults to EXOSIMS parameter list
- [x] download Sci-Eng Interface github


Completed Task: I added multi-node run support for my ARTES scripts using mpi4py. Fingers crossed this decreases runtimes overall

**Comment by cvancil** [comment]
## Nov 21

### **Completed Items and Updates:**
- ARTES Modeling:
     - [x] integrated mpi4py into code, now testing most efficient use of resources
     - [x] began discussions w/ Max about correlated noise & error bar size
- ExoEarth HWO Models:
     - [x] made table of all (I & Q) fluxes at 45deg, 90 deg phase angles (in V,R band)
     - [x] converted to useable flux units, arbitrarily scaled to 10 pc - ready to plug into ETCs
- HWO ETC:
     - [x] small updates to EXOSIMS param list based on feedback from meeting
     - [x] determined best path forward via chats w/ Max, JT, & WG

### **Todo-list Items from Last Meeting:**
- SIMP REU Project: (what's the due date for these kind of tasks)
     - [ ] Clean up REU proj description (I wrote this at 4am observing night, haven't reread yet)
     - [ ] Begin documentation of project (reduction process notes, general roadmap for student, can clean up past notebooks for reference)
- Luhman 16 Data Analysis:
     - [ ] NACO Cross-Correlation
     - [ ] BD Clouds Test: Downsample L16Grond Data to picaso-model native resolution (I have at least loaded these things into the same notebook, ready to work with)
- ARTES modeling:  
     -  (If resource allocation process fails) Find Some H-band spectra of L16AB to determine important wavelengths
 - HWO ETC:
      - [ ] Pick a science case, try to replicate same outputs from EXOSIMS & syotools
      - [ ] update syotools pseudocode to produce ideal SNRS for Kenny models
      - [x] invert Mennesson SNR equation -> get output exptime for desired SNR
          - outputs using this inversion make no sense (1e17 days). Triple checked math, should double check code & input flux values 

### **New Action Items:**
- [x] answer Max G and Theodora emails

**Comment by cvancil** [comment]
new cnsi issue - remote I/O error, cannot write files. this has wasted days of good computing time, none of results saved. figure out fix for issue

**Comment by cvancil** [comment]
## Dec 2

### **Completed Items and Updates:**
- [x] answer Max G and Theodora emails
- [x] fix remote I/O pod error and initiate many new ARTES runs

### **Todo-list Items from Last Meeting:**
- SIMP REU Project: (Due Dec 5)
     - [x] Clean up REU proj description
     - [ ] Begin documentation of project (reduction process notes, general roadmap for student, can clean up past notebooks for reference)
- Luhman 16 Data Analysis:
     - [ ] NACO Cross-Correlation
     - [ ] BD Clouds Test: Downsample L16Grond Data to picaso-model native resolution (I have at least loaded these things into the same notebook, ready to work with)
 - HWO ETC:
      - [ ] Pick a science case, try to replicate same outputs from EXOSIMS & syotools
      - [x] update syotools pseudocode to produce ideal SNRS for Kenny models
      - [x] invert Mennesson SNR equation -> get output exptime for desired SNR
          - outputs using this inversion make no sense (1e17 days). Triple checked math, should double check code & input flux values 

### **New Action Items:**
- [x] Send Max Update Slides about Luhman 16 for meeting tomorrow
     - [x] include future steps 
     - going to chat about future proposals, think about priorities for the Grant, L16AB was on the doc, so good for us to keep working on that
     - SIMP observations with WIRCPol, but don't see anything time varying
          - have a bunch of WIRCPol data, can simulate several scenarios for those, could put in a proposal to get 2 staright nights of SIMP (should we see anything time-varying in SIMP polarimetry?), Dmitri committed to submit Palomar proposals - could do Keck+Palomar simultaneous nights
          - Miradas instrument (?) high-resolution Luhman 16 proposal

**Comment by cvancil** [comment]
## December 9

### **Completed Items and Updates:**

### **Todo-list Items from Last Meeting:**

### **New Action Items:**

- Earth-Type Model Updates:
     - [x] waiting to receive Venus + updated Archean Earth Haze models from Kenny
     - if model file only has 3 valid wvs -> this is a broadband measurement
          - [x]  update code to look for these files too
     - [ ] RC ~10^-10, higher PP-contrast (arb. high), 5 pc, New Phase angles (135-150ish, ~40 deg, some longer ~160, etc.), do I/B band for Kenny, kick radius down to 1 Rearth
     - [ ] make a bunch of different plots to compare outputs w/ these parameters

- Write notes on Friday that describe where I am, and where to pick work back up after vacation
-  NACO-> good visual inspection good place to start, iun the lightc
- fit photometry to sinusoidal cloud models (?) think about photometry vs polarimetry phases (at center of target or at edges)
- daniel apai paper about TESS Luhman 16 sinusoidal models
- maybe skip ccf, because we are seeing high signal, low frequency changes -> still do it. but visual inspection weill get use most of the way there
- rotate Q/U -> rottion matrix with angle from MCMC fit or 90 degrees off of that
     - have to account for parallactic angle over time -> angle = parallactic angle + polarization angle TRY THIS ONE FIRST
     - another complication -> haven't done instrument calibration yet, which may rotate it 
          - look at Max's paper for how to do this

### Refer to HWO polarimetry modeling Github issue for next steps on ETC
